env:
  CIRRUS_CLONE_DEPTH: 1
  FEATURES: huge

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    pkg install -y gettext 
  build_script:
    - ./configure --with-features=$HUGE
    - make
  test_script:
    - make test
